import './styles/main.css';
import { initSmoothScroll } from './smooth-scroll.js';
import { initBloom } from './bloom.js';
import { initNav } from './nav.js';
import { initRgbMixer } from './rgb-mixer.js';
import { initColorSliders } from './color-sliders.js';
import { initQuantizeDemo } from './quantize-demo.js';
import { initBandingDemo } from './banding-demo.js';
import { initAudioButton } from './audio.js';
import { initMotion } from './motion.js';

initSmoothScroll();
initBloom();
initNav();
initRgbMixer();
initColorSliders();
initQuantizeDemo();
initBandingDemo();
initAudioButton();
initMotion();
